---
kind: pipeline
type: docker
name: default

steps:
  - name: go-build
    image: golang
    commands:
      - go build
  - name: docker
    image: plugins/docker
    settings:
      username: jakewalker
      password:
        from_secret: DOCKER_PASSWORD
      repo: jakewalker/telegram-cron-bot
      auto_tag: true
    when:
      branch:
        - master
      event:
        - push
        - tag
      repo:
        - jakew/telegram-cron-bot